// Code generated by logcopter-gen; DO NOT EDIT.

package slackdoc

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.discord-bot.pkg.slackdoc")
