// Code generated by logcopter-gen; DO NOT EDIT.

package slacktransport

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.discord-bot.internal.slacktransport")
